### ISSUE TITLE
CentOS 7 

### ISSUE THREAD

**Issue by Adriaanse** [jcefmaven/jcefdocker#1]
First of all I would like to compliment you on this project I see the way it is set up we can benefit from it in several ways.

The problem I am facing is that this Debian based build for linux does not work on CentOS 7, which we need to support for specific clients. The error: libjcef.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found

In the past we had similar problems when compiling JCEF for linux and the solution was to build it on CentOS 7, so I guess I can try to fork this project and use a centos:7 based docker image ?

**Comment by FriwiDev** [comment]
Yes, you can try this. CentOS 7 uses a very outdated version of glibc. You could try to install a current gcc on your target systems to possible fix the error at your clients or to derive a build script using outdated glibc from these docker containers. Please note that the actual build is invoked by forking the jcefbuild repository. Jcefdocker provides the environments, while jcefbuild issues the actual commands involved in building.
